# Use root/example as user/password credentials
version: '3'

services:

  db:
    image: wolffjose/mysqldbsampleapi:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /tmp/data:/var/lib/mysql  
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080